# Generated by Django 5.1.2 on 2024-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_name", models.CharField(max_length=30)),
                ("species", models.CharField(max_length=30)),
                ("adopter", models.CharField(max_length=30)),
                ("request_date", models.DateField(help_text="aaaa/mm/dd")),
                ("status", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Adoption",
                "verbose_name_plural": "Adoptions",
                "ordering": ["request_date"],
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("species", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
                ("breed", models.CharField(max_length=30)),
                ("health_history", models.TextField()),
            ],
            options={
                "verbose_name": "Animal",
                "verbose_name_plural": "Animals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=30)),
                ("role", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "ordering": ["name"],
            },
        ),
    ]
