# Generated by Django 4.2.16 on 2024-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0002_animal_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="animals/"),
        ),
    ]
