# Generated by Django 5.1.2 on 2024-10-30 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0004_animal_description_animal_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="animal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adoptions",
                to="shelter.animal",
            ),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under Review", "Em análise"),
                    ("Not Adopted", "Não adotado"),
                    ("Adopted", "Adotado"),
                ],
                default="Under Review",
                max_length=30,
            ),
        ),
    ]
