# Generated by Django 5.1.2 on 2024-10-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0005_adoption_animal_alter_adoption_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adoption",
            name="animal",
        ),
        migrations.AddField(
            model_name="adoption",
            name="adopter_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="adopter",
            field=models.CharField(max_length=254),
        ),
    ]
