# Generated by Django 5.1.2 on 2024-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0006_remove_adoption_animal_adoption_adopter_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="adopter",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="status",
            field=models.CharField(max_length=30),
        ),
    ]
