# Generated by Django 5.1.2 on 2024-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_alter_adoption_adopter_alter_adoption_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='adopter_email',
        ),
        migrations.AlterField(
            model_name='adoption',
            name='adopter',
            field=models.CharField(max_length=30),
        ),
    ]
