# Generated by Django 5.1.2 on 2024-10-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0008_remove_adoption_adopter_email_alter_adoption_adopter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('Under Review', 'Em análise'), ('Not Adopted', 'Não adotado'), ('Adopted', 'Adotado')], default='Under Review', max_length=30),
        ),
    ]
